version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./vector_db:/app/vector_db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 